language: go
go:
  - "1.x"

env: GO111MODULE=on CGO_ENABLED=0

install:
  - go mod download

script:
  - go build ./cmd/gomodproxy
  - go test -v ./...

deploy:
  provider: script
  script:
    - printf 'FROM scratch\nADD gomodproxy /\nCMD ["/gomodproxy"]' > Dockerfile
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t "sixt/gomodproxy" .
    - docker push "sixt/gomodproxy"
