language: go
go:
  - "1.x"

env: GO111MODULE=on CGO_ENABLED=0

install:
  - go mod download

script:
  - go build ./cmd/gomodproxy
  - go test -v ./...

after_success:
  - printf 'FROM scratch\nADD gomodproxy /\nCMD ["/gomodproxy"]' > Dockerfile
  - docker build -t "sixt/gomodproxy:latest" .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "sixt/gomodproxy:latest"
  - if [ ! -z $TRAVIS_TAG ] ; then
      docker tag sixt/gomodproxy:latest sixt/gomodproxy:$TRAVIS_TAG
      docker push sixt/gomodproxy:$TRAVIS_TAG
    fi
